# Generated by Django 5.2.17 on 2026-09-20 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_simplify_roles'),
        ('brokers', '0005_seed_plans'),
        ('professionals', '0004_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_type', models.CharField(choices=[('BROKER', 'Broker'), ('PROFESSIONAL', 'Professional')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=10)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='brokers.brokerorganization')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='professionals.professionalprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['email', 'accepted_at'], name='accounts_or_email_d5ed4b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('broker__isnull', False), ('org_type', 'BROKER'), ('professional__isnull', True)), models.Q(('broker__isnull', True), ('org_type', 'PROFESSIONAL'), ('professional__isnull', False)), _connector='OR'), name='accounts_invitation_one_organization')],
            },
        ),
    ]
