# Generated by Django 5.2.17 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
