# Generated by Django 5.2.17 on 2026-09-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='billing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='listings_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='messages_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
