import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#496171",
        "secondary-fixed-dim": "#7dd4d9",
        "on-secondary-fixed-variant": "#004f53",
        "surface-container-low": "#f5f3ee",
        "secondary-container": "#97eef3",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        background: "#fbf9f4",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e4e2dd",
        primary: "#001520",
        "surface-variant": "#e4e2dd",
        surface: "#fbf9f4",
        "on-surface-variant": "#42474b",
        "on-tertiary-container": "#a78a54",
        "on-secondary-fixed": "#002021",
        "tertiary-fixed": "#ffdea4",
        "on-tertiary-fixed": "#261900",
        "outline-variant": "#c2c7cc",
        "tertiary-container": "#352400",
        error: "#ba1a1a",
        "primary-container": "#102a38",
        "surface-bright": "#fbf9f4",
        "inverse-primary": "#b0cadc",
        "on-primary-container": "#7992a3",
        "surface-container-high": "#eae8e3",
        "on-primary-fixed": "#021e2c",
        "surface-dim": "#dbdad5",
        "on-background": "#1b1c19",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#5a4314",
        "tertiary-fixed-dim": "#e3c286",
        "on-error-container": "#93000a",
        secondary: "#00696e",
        "on-surface": "#1b1c19",
        "primary-fixed": "#cce6f9",
        tertiary: "#1b1100",
        "surface-container": "#f0eee9",
        "secondary-fixed": "#9af1f6",
        outline: "#73787c",
        "inverse-surface": "#30312e",
        "on-primary-fixed-variant": "#314a59",
        "on-secondary-container": "#006e73",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b0cadc",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "1rem",
        margin: "1.5rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.5rem",
        "space-2xl": "4rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "gutter-desktop": "2rem",
        gutter: "1.5rem",
        "margin-desktop": "3rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "title-lg": ["var(--font-plus-jakarta-sans)"],
        "body-sm": ["var(--font-plus-jakarta-sans)"],
        "headline-sm": ["var(--font-playfair-display)"],
        "display-hero": ["var(--font-playfair-display)"],
        "label-sm": ["var(--font-plus-jakarta-sans)"],
        "spec-num": ["var(--font-plus-jakarta-sans)"],
        "body-lg": ["var(--font-plus-jakarta-sans)"],
        "label-md": ["var(--font-plus-jakarta-sans)"],
        "body-md": ["var(--font-plus-jakarta-sans)"],
        "headline-lg": ["var(--font-playfair-display)"],
        "headline-md": ["var(--font-playfair-display)"],
        "title-md": ["var(--font-plus-jakarta-sans)"],
      },
      fontSize: {
        "title-lg": ["18px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "500" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
        "spec-num": ["15px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
};

export default config;
