# Generated by Django 5.2.17 on 2026-09-18 05:32

import services_catalog.services
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_it', models.CharField(blank=True, max_length=120)),
                ('name_es', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True, validators=[services_catalog.services.validate_category_slug])),
                ('description_en', models.TextField(blank=True)),
                ('description_it', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('icon_key', models.CharField(blank=True, max_length=64)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('has_seo_page', models.BooleanField(default=False)),
                ('seo_title_en', models.CharField(blank=True, max_length=180)),
                ('seo_title_it', models.CharField(blank=True, max_length=180)),
                ('seo_title_es', models.CharField(blank=True, max_length=180)),
                ('seo_description_en', models.CharField(blank=True, max_length=320)),
                ('seo_description_it', models.CharField(blank=True, max_length=320)),
                ('seo_description_es', models.CharField(blank=True, max_length=320)),
            ],
            options={
                'verbose_name': 'service category',
                'verbose_name_plural': 'service categories',
                'ordering': ('display_order', 'name_en'),
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='services_ca_is_acti_dbb35d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('slug__in', ('professionals',)), _negated=True), name='service_category_slug_not_reserved')],
            },
        ),
    ]
