# Generated by Django 5.2.17 on 2026-09-18 06:20

import django.db.models.deletion
import professionals.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
        ('services_catalog', '0002_seed_seo_service_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=160)),
                ('title_it', models.CharField(blank=True, max_length=160)),
                ('title_es', models.CharField(blank=True, max_length=160)),
                ('description_en', models.TextField(blank=True)),
                ('description_it', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('service_area', models.JSONField(blank=True, default=list, validators=[professionals.models.validate_service_area])),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_services', to='services_catalog.servicecategory')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='professionals.professionalprofile')),
            ],
            options={
                'ordering': ('category__display_order', 'title_en'),
                'indexes': [models.Index(fields=['is_active'], name='services_ca_is_acti_d6f4d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('professional', 'category', 'title_en'), name='unique_professional_category_title')],
            },
        ),
    ]
