# Generated by Django 5.2.17 on 2026-09-18 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_catalog', '0004_seed_combined_directory_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyDirectoryMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_kind', models.CharField(choices=[('SERVICE', 'Legacy service record'), ('PROVIDER', 'Legacy provider record')], max_length=16)),
                ('legacy_identifier', models.CharField(max_length=190)),
                ('legacy_slug', models.CharField(blank=True, max_length=190)),
                ('normalized_name', models.CharField(blank=True, max_length=190)),
                ('normalized_address', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(blank=True, choices=[('SERVICE_CATEGORY', 'Service category'), ('PROFESSIONAL_PROFILE', 'Professional profile')], max_length=32)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('resolution', models.CharField(choices=[('PENDING', 'Pending'), ('MAPPED', 'Mapped'), ('DUPLICATE_REVIEW', 'Duplicate — needs human review'), ('UNRESOLVED', 'Unresolved')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('legacy_kind', 'legacy_identifier'),
                'indexes': [models.Index(fields=['legacy_kind', 'legacy_slug'], name='services_ca_legacy__23de56_idx'), models.Index(fields=['resolution'], name='services_ca_resolut_fd94db_idx')],
                'constraints': [models.UniqueConstraint(fields=('legacy_kind', 'legacy_identifier'), name='unique_legacy_kind_identifier')],
            },
        ),
    ]
