# Generated by Django 5.2.17 on 2026-09-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_catalog', '0008_seed_broader_professional_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('USD', 'USD')], default='EUR', max_length=3),
        ),
    ]
