# Generated by Django 5.2.17 on 2026-09-19 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.CharField(choices=[('HOME', 'Home page'), ('BOAT_LIST', 'Boat list'), ('BOAT_DETAIL', 'Boat detail'), ('DIRECTORY', 'Directory'), ('GUIDES', 'Guides')], max_length=12)),
                ('sponsor', models.CharField(max_length=120)),
                ('headline', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, default='', max_length=500)),
                ('cta_label', models.CharField(blank=True, default='', max_length=60)),
                ('cta_url', models.URLField(blank=True, default='', max_length=500)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['placement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.CharField(blank=True, default='', max_length=400)),
                ('body', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('hero_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('author_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=9)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
