# Generated by Django 5.2.17 on 2026-09-20 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_broker_about'),
        ('content', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='brokers.brokerorganization'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='professionals.professionalprofile'),
        ),
    ]
