# Generated by Django 5.2.17 on 2026-09-21 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0012_boatlisting_featured_at_boatlisting_featured_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name_en', models.CharField(max_length=80)),
                ('name_it', models.CharField(blank=True, default='', max_length=80)),
                ('name_es', models.CharField(blank=True, default='', max_length=80)),
                ('days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('is_popular', models.BooleanField(default=False, help_text="Shows a 'Most popular' mark")),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'days'],
                'constraints': [models.CheckConstraint(condition=models.Q(('days__gt', 0)), name='promotions_plan_days_positive'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='promotions_plan_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='ListingPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting payment'), ('PAID', 'Paid'), ('REVIEW', 'Needs staff review'), ('CANCELED', 'Canceled')], default='PENDING', max_length=8)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', max_length=128)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=128)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='listings.boatlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='promotions.promotionplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'status'], name='promotions_listing_status')],
            },
        ),
    ]
