# Generated by Django 5.2.17 on 2026-09-21 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_boatlisting_featured_at_boatlisting_featured_until'),
        ('professionals', '0008_professionalprofile_featured_at_and_more'),
        ('promotions', '0002_default_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpromotion',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='professionals.professionalprofile'),
        ),
        migrations.AlterField(
            model_name='listingpromotion',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='listings.boatlisting'),
        ),
        migrations.AddConstraint(
            model_name='listingpromotion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('listing__isnull', False), ('professional__isnull', True)), models.Q(('listing__isnull', True), ('professional__isnull', False)), _connector='OR'), name='promotions_exactly_one_target'),
        ),
    ]
