# Generated by Django 5.2.17 on 2026-09-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_boatlisting_featured_at_boatlisting_featured_until'),
        ('professionals', '0008_professionalprofile_featured_at_and_more'),
        ('promotions', '0003_listingpromotion_professional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_stats', to='listings.boatlisting')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_stats', to='professionals.professionalprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('listing', 'day'), name='promo_stat_unique_listing_day'), models.UniqueConstraint(condition=models.Q(('professional__isnull', False)), fields=('professional', 'day'), name='promo_stat_unique_professional_day'), models.CheckConstraint(condition=models.Q(models.Q(('listing__isnull', False), ('professional__isnull', True)), models.Q(('listing__isnull', True), ('professional__isnull', False)), _connector='OR'), name='promo_stat_exactly_one_target')],
            },
        ),
    ]
