# Generated by Django 5.2.17 on 2026-09-23 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('locale', models.CharField(max_length=2)),
                ('subject', models.CharField(max_length=200)),
                ('html_body', models.TextField(help_text='Rendered inside the shared Nautelo header/hero/footer layout.')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('key', 'locale'),
                'constraints': [models.UniqueConstraint(fields=('key', 'locale'), name='emailing_one_template_per_key_and_locale')],
            },
        ),
    ]
