# Generated by Django 5.2.17 on 2026-09-18 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0007_backfill_snapshot_finance_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewer_type', models.CharField(choices=[('USER', 'Authenticated user'), ('ANONYMOUS', 'Anonymous')], max_length=9)),
                ('viewer_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('first_viewed_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('user_agent_class', models.CharField(choices=[('HUMAN', 'Human'), ('BOT', 'Bot'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=7)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='listings.boatlisting')),
                ('viewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['listing', '-last_seen_at'],
                'indexes': [models.Index(fields=['listing', 'first_viewed_at'], name='analytics_l_listing_253448_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('viewer_user__isnull', False)), fields=('listing', 'viewer_user'), name='analytics_view_unique_user_per_listing'), models.UniqueConstraint(condition=models.Q(('viewer_hash__isnull', False)), fields=('listing', 'viewer_hash'), name='analytics_view_unique_hash_per_listing'), models.CheckConstraint(condition=models.Q(models.Q(('viewer_hash__isnull', True), ('viewer_user__isnull', False)), models.Q(('viewer_hash__isnull', False), ('viewer_user__isnull', True)), _connector='OR'), name='analytics_view_exactly_one_identity'), models.CheckConstraint(condition=models.Q(models.Q(('viewer_type', 'USER'), ('viewer_user__isnull', False)), models.Q(('viewer_type', 'ANONYMOUS'), ('viewer_user__isnull', True)), _connector='OR'), name='analytics_view_type_matches_identity'), models.CheckConstraint(condition=models.Q(('viewer_hash__isnull', True), ('viewer_hash__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='analytics_view_hash_is_lowercase_sha256_hex'), models.CheckConstraint(condition=models.Q(('last_seen_at__gte', models.F('first_viewed_at'))), name='analytics_view_last_seen_not_before_first_viewed')],
            },
        ),
    ]
