# Generated by Django 5.2.17 on 2026-09-20 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='professional-membership', max_length=40, unique=True)),
                ('name', models.CharField(default='Professional membership', max_length=120)),
                ('tagline', models.CharField(blank=True, default='', max_length=300)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=49, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=64)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), _negated=True), models.Q(('stripe_price_id', ''), _negated=True), _connector='OR'), name='professional_plan_active_needs_stripe_price')],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('LAPSED', 'Lapsed'), ('CANCELED', 'Canceled')], default='INACTIVE', max_length=10)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=64)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('past_due_since', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='professionals.professionalprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('stripe_subscription_id', ''), _negated=True), fields=('stripe_subscription_id',), name='professional_subscription_one_row_per_stripe_subscription')],
            },
        ),
    ]
