# Generated by Django 5.2.17 on 2026-09-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalplan',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Free days before the first charge; a card is still collected up front. 0 = no trial.'),
        ),
        migrations.AddField(
            model_name='professionalsubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalsubscription',
            name='trial_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalsubscription',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('TRIALING', 'Free trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('LAPSED', 'Lapsed'), ('CANCELED', 'Canceled')], default='INACTIVE', max_length=10),
        ),
    ]
