# Generated by Django 5.2.17 on 2026-09-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0006_org_image_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='place_geoname_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
