# Generated by Django 5.2.17 on 2026-09-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0007_professionalprofile_place_geoname_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='featured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='featured_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
