# Generated by Django 5.2.17 on 2026-09-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0008_professionalprofile_featured_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalsubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
