# Generated by Django 5.2.17 on 2026-09-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.PositiveBigIntegerField(unique=True)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('admin1_code', models.CharField(max_length=20)),
                ('name_en', models.CharField(max_length=150)),
                ('name_it', models.CharField(blank=True, default='', max_length=150)),
                ('name_es', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'ordering': ['country_code', 'name_en'],
                'constraints': [models.UniqueConstraint(fields=('country_code', 'admin1_code'), name='places_region_unique_code')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.PositiveBigIntegerField(unique=True)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('name_en', models.CharField(max_length=200)),
                ('name_it', models.CharField(blank=True, default='', max_length=200)),
                ('name_es', models.CharField(blank=True, default='', max_length=200)),
                ('ascii_name', models.CharField(max_length=200)),
                ('search_text', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('population', models.PositiveIntegerField(default=0)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='places.region')),
            ],
            options={
                'ordering': ['-population', 'name_en'],
                'indexes': [models.Index(fields=['country_code', 'region'], name='places_city_country_region')],
            },
        ),
    ]
