# Generated by Django 5.2.17 on 2026-09-21 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('source_en', models.TextField(help_text='The English text written in the code. Change it in the code, not here.')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Off once the code no longer uses the key.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'text',
                'verbose_name_plural': 'site texts',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='TextRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'EN'), ('it', 'IT'), ('es', 'ES')], max_length=2)),
                ('text', models.TextField(blank=True, help_text='The working text. It goes live when you press Publish to platform.')),
                ('published_text', models.TextField(blank=True, editable=False)),
                ('origin', models.CharField(choices=[('SOURCE', 'Written in the code'), ('MACHINE', 'Machine translation'), ('HUMAN', 'Edited by staff')], default='MACHINE', max_length=10)),
                ('stale', models.BooleanField(default=False, help_text='Waiting for a machine translation, or the English changed after a staff edit.')),
                ('attempts', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Failed machine translation tries; it stops at 3.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='uitext.textkey')),
            ],
            options={
                'ordering': ('key__key', 'locale'),
                'constraints': [models.UniqueConstraint(fields=('key', 'locale'), name='uitext_one_value_per_locale')],
            },
        ),
    ]
