# Generated by Django 5.2.17 on 2026-09-18 16:54

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0007_backfill_snapshot_finance_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitlement_type', models.CharField(choices=[('FREE_LISTING', 'Free listing'), ('PAID_LISTING', 'Paid listing'), ('MEDIA_UPGRADE', 'Media upgrade')], max_length=16)),
                ('source', models.CharField(choices=[('FREE_POLICY', 'Free policy'), ('STRIPE_PURCHASE', 'Stripe purchase'), ('STAFF_GRANT', 'Staff grant')], max_length=16)),
                ('source_payment_id', models.UUIDField(blank=True, null=True)),
                ('state', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('CONSUMED', 'Consumed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='AVAILABLE', max_length=16)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='listings.boatlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'entitlement_type', 'state'], name='entitlement_user_id_a622a5_idx'), models.Index(fields=['state', 'valid_until'], name='entitlement_state_6e2a4e_idx'), models.Index(fields=['user', 'entitlement_type', '-consumed_at'], name='entitlement_user_id_a7ed83_idx'), models.Index(fields=['state', 'reserved_at'], name='entitlement_state_6e74db_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='entitlements_validity_window_is_forward'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'CONSUMED'), _negated=True), ('consumed_at__isnull', False), _connector='OR'), name='entitlements_consumed_requires_consumed_at'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'RESERVED'), _negated=True), ('reserved_at__isnull', False), _connector='OR'), name='entitlements_reserved_requires_reserved_at'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'REVOKED'), _negated=True), ('revoked_at__isnull', False), _connector='OR'), name='entitlements_revoked_requires_revoked_at'), models.UniqueConstraint(condition=models.Q(('listing__isnull', False), models.Q(('state', 'REVOKED'), _negated=True)), fields=('listing', 'entitlement_type'), name='entitlements_one_live_right_per_listing_and_type')],
            },
        ),
    ]
