# Generated by Django 5.2.17 on 2026-09-18 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0002_seed_individual_entitlements_flag'),
        ('listings', '0008_boatlisting_consumed_entitlement'),
        ('payments', '0003_processedwebhookevent_paymentorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentitlement',
            name='source_payment_id',
        ),
        migrations.AddField(
            model_name='userentitlement',
            name='source_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='granted_entitlements', to='payments.paymentorder'),
        ),
        migrations.AddConstraint(
            model_name='userentitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('source_payment__isnull', False), models.Q(('state', 'REVOKED'), _negated=True)), fields=('source_payment',), name='entitlements_one_live_right_per_payment'),
        ),
    ]
