# Generated by Django 5.2.17 on 2026-09-20 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0003_remove_userentitlement_source_payment_id_and_more'),
        ('listings', '0010_boatlisting_slug'),
        ('payments', '0003_processedwebhookevent_paymentorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userentitlement',
            name='entitlements_one_live_right_per_listing_and_type',
        ),
        migrations.RemoveConstraint(
            model_name='userentitlement',
            name='entitlements_one_live_right_per_payment',
        ),
        migrations.AddField(
            model_name='userentitlement',
            name='grant_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userentitlement',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='userentitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', False), ('is_renewal', False), models.Q(('state', 'REVOKED'), _negated=True)), fields=('listing', 'entitlement_type'), name='entitlements_one_live_right_per_listing_and_type'),
        ),
        migrations.AddConstraint(
            model_name='userentitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('source_payment__isnull', False), models.Q(('state', 'REVOKED'), _negated=True)), fields=('source_payment', 'grant_index'), name='entitlements_one_live_right_per_payment'),
        ),
    ]
