# Generated by Django 5.2.17 on 2026-09-19 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRouterModel',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('context_length', models.BigIntegerField(blank=True, null=True)),
                ('max_completion_tokens', models.BigIntegerField(blank=True, null=True)),
                ('input_modalities', models.JSONField(blank=True, default=list)),
                ('output_modalities', models.JSONField(blank=True, default=list)),
                ('modality', models.CharField(blank=True, max_length=100)),
                ('prompt_price', models.DecimalField(blank=True, decimal_places=12, help_text='USD per token', max_digits=24, null=True)),
                ('completion_price', models.DecimalField(blank=True, decimal_places=12, help_text='USD per token', max_digits=24, null=True)),
                ('supported_parameters', models.JSONField(blank=True, default=list)),
                ('is_moderated', models.BooleanField(default=False)),
                ('created_remote_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='False once OpenRouter stops listing the model.')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenRouter model',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TranslationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('temperature', models.FloatField(default=0.2, help_text='0 = literal, 1 = creative. Translation works best low.')),
                ('max_input_chars', models.PositiveIntegerField(default=6000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(blank=True, help_text='Only models that return text are offered. Type to search.', limit_choices_to=models.Q(('is_available', True), ('output_modalities__contains', ['text'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='translation.openroutermodel')),
            ],
            options={
                'verbose_name': 'translation settings',
                'verbose_name_plural': 'translation settings',
            },
        ),
    ]
