# Generated by Django 5.2.17 on 2026-09-21 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationsettings',
            name='ui_enabled',
            field=models.BooleanField(default=True, help_text="Translate the site's interface text (buttons, headings, labels) into Italian and Spanish."),
        ),
        migrations.AddField(
            model_name='translationsettings',
            name='ui_model',
            field=models.ForeignKey(blank=True, help_text='Model for the interface text. Leave empty to use the listing model above.', limit_choices_to=models.Q(('is_available', True), ('output_modalities__contains', ['text'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='translation.openroutermodel'),
        ),
    ]
