# Generated by Django 5.2.17 on 2026-09-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_seed_finance_estimates_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Only for staff: what this row is.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('country_code', models.CharField(help_text='ISO code, e.g. ES or IT. Operations are national only.', max_length=2)),
                ('product', models.CharField(choices=[('LOAN', 'Loan / mortgage'), ('LEASING', 'Leasing (with purchase option)')], max_length=10)),
                ('condition', models.CharField(choices=[('ANY', 'Any'), ('NEW', 'New'), ('USED', 'Used')], default='ANY', max_length=4)),
                ('use', models.CharField(choices=[('ANY', 'Any'), ('PRIVATE', 'Private'), ('COMPANY', 'Company / charter')], default='ANY', max_length=8)),
                ('tin_percent', models.DecimalField(decimal_places=3, help_text='Nominal yearly rate used for the payment.', max_digits=6)),
                ('tae_percent', models.DecimalField(blank=True, decimal_places=3, help_text='Effective rate shown in the representative example.', max_digits=6, null=True)),
                ('opening_fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='One-off fee, % of the financed amount.', max_digits=5)),
                ('residual_percent', models.DecimalField(decimal_places=2, default=0, help_text='Leasing purchase option, % of the price, paid at the end.', max_digits=5)),
                ('min_price', models.DecimalField(decimal_places=2, default=15000, max_digits=12)),
                ('max_price', models.DecimalField(decimal_places=2, default=2000000, max_digits=12)),
                ('min_down_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_down_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('default_down_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('terms_years', models.JSONField(default=list, help_text='Allowed terms in years, e.g. [5, 7, 10, 15].')),
                ('max_age_at_end_years', models.PositiveSmallIntegerField(blank=True, help_text='Used boats: boat age when the contract ends must not exceed this.', null=True)),
                ('age_plus_term_limit', models.PositiveSmallIntegerField(blank=True, help_text='Used boats: boat age + term in years must not exceed this (e.g. 35).', null=True)),
                ('vat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vat_on_installment', models.BooleanField(default=False, help_text='Leasing instalments carry VAT that a private buyer cannot recover.')),
                ('vat_recoverable', models.BooleanField(default=False, help_text='Companies can deduct that VAT, so the simulator leads with the instalment without VAT.')),
                ('representative_months', models.PositiveSmallIntegerField(default=120)),
                ('note_en', models.TextField(blank=True, default='', help_text='Shown under the result for this row.')),
                ('note_it', models.TextField(blank=True, default='')),
                ('note_es', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['sort_order', 'country_code', 'product', 'condition', 'use'],
                'constraints': [models.UniqueConstraint(fields=('country_code', 'product', 'condition', 'use'), name='finance_rule_unique_combo')],
            },
        ),
    ]
