# Generated by Django 5.2.17 on 2026-09-18 23:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('INDIVIDUAL_LISTING_RIGHT', 'Individual listing right'), ('LISTING_MEDIA_UPGRADE', 'Listing media upgrade')], max_length=32, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_it', models.CharField(blank=True, default='', max_length=120)),
                ('name_es', models.CharField(blank=True, default='', max_length=120)),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_it', models.TextField(blank=True, default='')),
                ('description_es', models.TextField(blank=True, default='')),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=64)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=64)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('display_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entitlement_valid_days', models.PositiveIntegerField(default=365)),
                ('publication_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__in', ['INDIVIDUAL_LISTING_RIGHT', 'LISTING_MEDIA_UPGRADE'])), name='payments_product_code_is_known'), models.CheckConstraint(condition=models.Q(('display_amount__gte', 0)), name='payments_product_amount_is_not_negative'), models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='payments_product_currency_is_iso4217'), models.CheckConstraint(condition=models.Q(('entitlement_valid_days__gt', 0)), name='payments_product_validity_is_positive'), models.CheckConstraint(condition=models.Q(('publication_days__isnull', True), ('publication_days__gt', 0), _connector='OR'), name='payments_product_publication_days_is_positive_or_null'), models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), _negated=True), models.Q(('display_amount__gt', 0), models.Q(('stripe_product_id', ''), _negated=True), models.Q(('stripe_price_id', ''), _negated=True)), _connector='OR'), name='payments_product_active_is_fully_configured')],
            },
        ),
    ]
