# Generated by Django 5.2.17 on 2026-09-18 23:29

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0002_seed_individual_entitlements_flag'),
        ('listings', '0008_boatlisting_consumed_entitlement'),
        ('payments', '0002_seed_products_and_checkout_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('payload_checksum', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('RECEIVED', 'Received'), ('FULFILLED', 'Fulfilled'), ('ALREADY_FULFILLED', 'Already fulfilled'), ('IGNORED', 'Ignored'), ('MISMATCH', 'Mismatch'), ('GRANT_CONFLICT', 'Grant conflict'), ('ORDER_NOT_FOUND', 'Order not found'), ('EXPIRED', 'Expired'), ('REFUND_HANDLED', 'Refund handled'), ('DISPUTE_HANDLED', 'Dispute handled')], default='RECEIVED', max_length=24)),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['event_type', '-processed_at'], name='payments_pr_event_t_cbb240_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('result__in', ['ALREADY_FULFILLED', 'DISPUTE_HANDLED', 'EXPIRED', 'FULFILLED', 'GRANT_CONFLICT', 'IGNORED', 'MISMATCH', 'ORDER_NOT_FOUND', 'RECEIVED', 'REFUND_HANDLED'])), name='payments_webhook_result_is_known')],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CHECKOUT_OPEN', 'Checkout open'), ('PAID', 'Paid'), ('FULFILLED', 'Fulfilled'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], default='CREATED', max_length=16)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', max_length=128)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('client_idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_entitlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_orders', to='entitlements.userentitlement')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='listings.boatlisting')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.marketplaceproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_pa_user_id_367e5d_idx'), models.Index(fields=['product', 'status'], name='payments_pa_product_82c1fc_idx'), models.Index(fields=['status', 'created_at'], name='payments_pa_status_c33817_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_order_amount_is_positive'), models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='payments_order_currency_is_iso4217'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['DISPUTED', 'FULFILLED', 'PAID', 'REFUNDED']), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='payments_order_paid_requires_paid_at'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'FULFILLED'), _negated=True), models.Q(('fulfilled_entitlement__isnull', False), ('fulfilled_at__isnull', False)), _connector='OR'), name='payments_order_fulfilled_requires_entitlement_and_stamp'), models.UniqueConstraint(condition=models.Q(('stripe_checkout_session_id', ''), _negated=True), fields=('stripe_checkout_session_id',), name='payments_order_one_row_per_checkout_session'), models.UniqueConstraint(condition=models.Q(('stripe_payment_intent_id', ''), _negated=True), fields=('stripe_payment_intent_id',), name='payments_order_one_row_per_payment_intent'), models.UniqueConstraint(condition=models.Q(('client_idempotency_key', ''), _negated=True), fields=('user', 'client_idempotency_key'), name='payments_order_one_row_per_client_idempotency_key')],
            },
        ),
    ]
