# Generated by Django 5.2.17 on 2026-09-20 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0004_remove_userentitlement_entitlements_one_live_right_per_listing_and_type_and_more'),
        ('listings', '0010_boatlisting_slug'),
        ('payments', '0003_processedwebhookevent_paymentorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='payments_order_quantity_is_positive'),
        ),
    ]
