# Generated by Django 5.2.17 on 2026-09-20 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_listing_right_to_paid_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_it', models.CharField(blank=True, default='', max_length=120)),
                ('name_es', models.CharField(blank=True, default='', max_length=120)),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_it', models.TextField(blank=True, default='')),
                ('description_es', models.TextField(blank=True, default='')),
                ('publication_days', models.PositiveIntegerField()),
                ('image_limit', models.PositiveSmallIntegerField(default=20)),
                ('video_limit', models.PositiveSmallIntegerField(default=1)),
                ('display_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=64)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'publication_days'],
                'constraints': [models.CheckConstraint(condition=models.Q(('publication_days__gt', 0)), name='payments_package_days_positive'), models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), _negated=True), models.Q(('display_amount__gt', 0), models.Q(('stripe_product_id', ''), _negated=True), models.Q(('stripe_price_id', ''), _negated=True)), _connector='OR'), name='payments_package_active_is_fully_configured')],
            },
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.listingpackage'),
        ),
    ]
