# Generated by Django 5.2.17 on 2026-09-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0012_boatlisting_featured_at_boatlisting_featured_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_version', models.PositiveIntegerField()),
                ('model_name', models.CharField(max_length=120)),
                ('text_hash', models.CharField(max_length=64)),
                ('vector', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='listings.boatlisting')),
            ],
        ),
    ]
