# Generated by Django 5.2.17 on 2026-09-18 00:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('taxonomy', '0002_boatmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_type', models.CharField(choices=[('PRIVATE', 'Private seller'), ('BROKER', 'Broker')], max_length=7)),
                ('custom_model_name', models.CharField(blank=True, default='', max_length=100)),
                ('manufacture_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('show_finance_estimate', models.BooleanField(default=False)),
                ('finance_down_payment_override_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('finance_rate_override_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('finance_term_override_months', models.PositiveIntegerField(blank=True, null=True)),
                ('publication_source', models.CharField(blank=True, choices=[('FREE_ENTITLEMENT', 'Free entitlement'), ('PAID_ENTITLEMENT', 'Paid entitlement'), ('BROKER_POLICY', 'Broker policy')], default='', max_length=16)),
                ('consumed_entitlement_id', models.UUIDField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('view_count_cached', models.BigIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='taxonomy.boatbrand')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='brokers.brokerorganization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='taxonomy.boatmodel')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_listings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='listings_bo_status_df91ff_idx'), models.Index(fields=['owner_user', 'status'], name='listings_bo_owner_u_dfcc0f_idx'), models.Index(fields=['broker', 'status'], name='listings_bo_broker__6509f6_idx'), models.Index(fields=['expires_at'], name='listings_bo_expires_7cc7af_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('seller_type', 'PRIVATE'), _negated=True), models.Q(('owner_user__isnull', False), ('broker__isnull', True)), _connector='OR'), name='listings_private_requires_owner_and_no_broker'), models.CheckConstraint(condition=models.Q(models.Q(('seller_type', 'BROKER'), _negated=True), models.Q(('broker__isnull', False), ('owner_user__isnull', True)), _connector='OR'), name='listings_broker_requires_org_and_no_owner'), models.CheckConstraint(condition=models.Q(('show_finance_estimate', False), ('seller_type', 'BROKER'), _connector='OR'), name='listings_finance_flag_requires_broker'), models.CheckConstraint(condition=models.Q(('manufacture_year__gte', 1900)), name='listings_manufacture_year_at_least_1900'), models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gt', 0), _connector='OR'), name='listings_price_is_positive_when_present'), models.CheckConstraint(condition=models.Q(('custom_model_name', ''), ('custom_model_name__regex', '^.{2,100}$'), _connector='OR'), name='listings_custom_model_name_length_2_to_100')],
            },
        ),
    ]
