# Generated by Django 5.2.17 on 2026-09-18 00:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_boatlisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=5)),
                ('storage_key', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('SCANNING', 'Scanning'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('REJECTED', 'Rejected')], default='UPLOADING', max_length=10)),
                ('mime_type', models.CharField(max_length=100)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='listings.boatlisting')),
            ],
            options={
                'ordering': ['media_type', 'sort_order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'storage_key'), name='listings_media_unique_storage_key_per_listing'), models.UniqueConstraint(fields=('listing', 'media_type', 'sort_order'), name='listings_media_unique_sort_order_per_type'), models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='listings_media_byte_size_is_positive'), models.CheckConstraint(condition=models.Q(('checksum_sha256__regex', '^[0-9a-f]{64}$')), name='listings_media_checksum_is_lowercase_sha256_hex')],
            },
        ),
    ]
