# Generated by Django 5.2.17 on 2026-09-18 01:00

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingmedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes requested'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=17)),
                ('origin', models.CharField(choices=[('OWNER', 'Owner'), ('STAFF_CORRECTION', 'Staff correction')], default='OWNER', max_length=16)),
                ('payload', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_listing_revisions', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='listings.boatlisting')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_listing_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['listing', '-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='ListingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('brand_name_snapshot', models.CharField(max_length=150)),
                ('model_name_snapshot', models.CharField(max_length=150)),
                ('custom_model_name_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('manufacture_year_snapshot', models.PositiveSmallIntegerField()),
                ('title_en', models.CharField(max_length=200)),
                ('title_it', models.CharField(blank=True, default='', max_length=200)),
                ('title_es', models.CharField(blank=True, default='', max_length=200)),
                ('description_en', models.TextField()),
                ('description_it', models.TextField(blank=True, default='')),
                ('description_es', models.TextField(blank=True, default='')),
                ('specifications', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('specifications_schema_version', models.PositiveIntegerField(default=1)),
                ('location_country', models.CharField(max_length=2)),
                ('location_region', models.CharField(blank=True, default='', max_length=120)),
                ('location_city', models.CharField(max_length=120)),
                ('currency', models.CharField(max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('media_manifest', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('approved_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_snapshots', to='listings.listingrevision')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='listings.boatlisting')),
            ],
            options={
                'ordering': ['listing', '-version'],
            },
        ),
        migrations.AddField(
            model_name='listingrevision',
            name='base_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='based_revisions', to='listings.listingsnapshot'),
        ),
        migrations.AddField(
            model_name='boatlisting',
            name='current_public_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='listings.listingsnapshot'),
        ),
        migrations.AddConstraint(
            model_name='listingsnapshot',
            constraint=models.UniqueConstraint(fields=('listing', 'version'), name='listings_snapshot_unique_version_per_listing'),
        ),
        migrations.AddConstraint(
            model_name='listingsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='listings_snapshot_version_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='listingsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='listings_snapshot_price_is_positive'),
        ),
        migrations.AddIndex(
            model_name='listingrevision',
            index=models.Index(fields=['state', 'submitted_at'], name='listings_li_state_f7faeb_idx'),
        ),
        migrations.AddConstraint(
            model_name='listingrevision',
            constraint=models.UniqueConstraint(fields=('listing', 'revision_number'), name='listings_revision_unique_number_per_listing'),
        ),
        migrations.AddConstraint(
            model_name='listingrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('DRAFT', 'SUBMITTED'))), fields=('listing',), name='listings_revision_one_open_per_listing'),
        ),
        migrations.AddConstraint(
            model_name='listingrevision',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'DRAFT'), models.Q(('submitted_by__isnull', False), ('submitted_at__isnull', False)), _connector='OR'), name='listings_revision_non_draft_requires_submission_stamps'),
        ),
        migrations.AddConstraint(
            model_name='listingrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ('APPROVED', 'CHANGES_REQUESTED', 'REJECTED')), _negated=True), models.Q(('decided_by__isnull', False), ('decided_at__isnull', False)), _connector='OR'), name='listings_revision_decided_requires_decision_stamps'),
        ),
        migrations.AddConstraint(
            model_name='listingrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ('CHANGES_REQUESTED', 'REJECTED')), _negated=True), models.Q(('decision_note', ''), _negated=True), _connector='OR'), name='listings_revision_refusal_requires_a_note'),
        ),
        migrations.AddConstraint(
            model_name='listingrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='listings_revision_number_is_positive'),
        ),
    ]
