# Generated by Django 5.2.17 on 2026-09-18 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        ('listings', '0004_seed_listing_revisions_flag'),
        ('taxonomy', '0002_boatmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boatlisting',
            constraint=models.CheckConstraint(condition=models.Q(('finance_down_payment_override_percent__isnull', True), models.Q(('finance_down_payment_override_percent__gte', 0), ('finance_down_payment_override_percent__lte', 99.99)), _connector='OR'), name='listings_finance_down_payment_override_percent_0_to_99_99'),
        ),
        migrations.AddConstraint(
            model_name='boatlisting',
            constraint=models.CheckConstraint(condition=models.Q(('finance_rate_override_percent__isnull', True), models.Q(('finance_rate_override_percent__gte', 0), ('finance_rate_override_percent__lte', 100)), _connector='OR'), name='listings_finance_rate_override_percent_0_to_100'),
        ),
    ]
