# Generated by Django 5.2.17 on 2026-09-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_finance_override_percent_bounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsnapshot',
            name='finance_down_payment_override_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='listingsnapshot',
            name='finance_rate_override_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='listingsnapshot',
            name='finance_term_override_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingsnapshot',
            name='show_finance_estimate',
            field=models.BooleanField(default=False),
        ),
    ]
