# Generated by Django 5.2.17 on 2026-09-18 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0002_seed_individual_entitlements_flag'),
        ('listings', '0007_backfill_snapshot_finance_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatlisting',
            name='consumed_entitlement_id',
        ),
        migrations.AddField(
            model_name='boatlisting',
            name='consumed_entitlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entitlements.userentitlement'),
        ),
    ]
