# Generated by Django 5.2.17 on 2026-09-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_boatlisting_consumed_entitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmedia',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
