# Generated by Django 5.2.17 on 2026-09-19 05:25

from django.db import migrations, models


def backfill_slugs(apps, schema_editor):
    from django.utils.text import slugify

    BoatListing = apps.get_model("listings", "BoatListing")
    rows = BoatListing.objects.filter(
        slug__isnull=True, current_public_snapshot__isnull=False
    ).select_related("brand", "model")
    for listing in rows:
        base = slugify(
            f"{listing.brand.name} {listing.model.name} "
            f"{listing.manufacture_year} {listing.pk.hex[:8]}"
        )[:190]
        listing.slug = base
        listing.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listingmedia_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatlisting',
            name='slug',
            field=models.SlugField(blank=True, max_length=190, null=True, unique=True),
        ),
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
    ]
