# Generated by Django 5.2.17 on 2026-09-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_boatlisting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsnapshot',
            name='location_place_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
