# Generated by Django 5.2.17 on 2026-09-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listingsnapshot_location_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatlisting',
            name='featured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boatlisting',
            name='featured_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
