# Generated by Django 5.2.17 on 2026-09-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_boatlisting_featured_at_boatlisting_featured_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatlisting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
