# Generated by Django 5.2.17 on 2026-09-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0013_boatlisting_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boatlisting",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending approval"),
                    ("PUBLISHED", "Published"),
                    ("REJECTED", "Rejected"),
                    ("SUSPENDED", "Suspended"),
                    ("PAUSED", "Paused"),
                    ("EXPIRED", "Expired"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=16,
            ),
        ),
    ]
