# Generated by Django 5.2.17 on 2026-09-21 05:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(choices=[('general', 'General'), ('buying', 'Buying'), ('selling', 'Selling'), ('brokers', 'Brokers'), ('services', 'Services'), ('financing', 'Financing'), ('press', 'Press')], max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('message', models.TextField(blank=True, default='', max_length=4000)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('reply_language', models.CharField(default='EN', max_length=2)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('HANDLED', 'Handled')], default='NEW', max_length=8)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
