# Generated by Django 5.2.17 on 2026-09-18 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('listings', '0007_backfill_snapshot_finance_settings'),
        ('professionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_type', models.CharField(choices=[('LISTING_INQUIRY', 'Listing inquiry'), ('BROKER_INQUIRY', 'Broker inquiry'), ('PROFESSIONAL_INQUIRY', 'Professional inquiry'), ('SUPPORT', 'Support')], max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ARCHIVED', 'Archived'), ('BLOCKED', 'Blocked')], default='OPEN', max_length=10)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='brokers.brokerorganization')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_conversations', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='listings.boatlisting')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='professionals.professionalprofile')),
            ],
            options={
                'ordering': ('-last_message_at', '-created_at'),
                'indexes': [models.Index(fields=['initiator', '-last_message_at'], name='messaging_c_initiat_557db7_idx'), models.Index(fields=['broker', '-last_message_at'], name='messaging_c_broker__99d95e_idx'), models.Index(fields=['professional', '-last_message_at'], name='messaging_c_profess_50c356_idx'), models.Index(fields=['listing', '-last_message_at'], name='messaging_c_listing_50d82e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('conversation_type', 'LISTING_INQUIRY'), ('listing__isnull', False), ('professional__isnull', True)), models.Q(('broker__isnull', False), ('conversation_type', 'BROKER_INQUIRY'), ('listing__isnull', True), ('professional__isnull', True)), models.Q(('broker__isnull', True), ('conversation_type', 'PROFESSIONAL_INQUIRY'), ('listing__isnull', True), ('professional__isnull', False)), models.Q(('broker__isnull', True), ('conversation_type', 'SUPPORT'), ('listing__isnull', True), ('professional__isnull', True)), _connector='OR'), name='messaging_conversation_exactly_one_context'), models.UniqueConstraint(condition=models.Q(('listing__isnull', False), ('status', 'OPEN')), fields=('initiator', 'listing'), name='messaging_open_listing_thread_unique'), models.UniqueConstraint(condition=models.Q(('broker__isnull', False), ('listing__isnull', True), ('status', 'OPEN')), fields=('initiator', 'broker'), name='messaging_open_broker_thread_unique'), models.UniqueConstraint(condition=models.Q(('professional__isnull', False), ('status', 'OPEN')), fields=('initiator', 'professional'), name='messaging_open_professional_thread_unique')],
            },
        ),
    ]
