# Generated by Django 5.2.17 on 2026-09-18 19:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
        ('messaging', '0002_seed_unified_inquiries_flag'),
        ('professionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('BROKER', 'Broker'), ('PROFESSIONAL', 'Professional')], max_length=12)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_access_grants', to='brokers.brokerorganization')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_access_grants', to='professionals.professionalprofile')),
                ('source_conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_access_grants', to='messaging.conversation')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-granted_at',),
                'indexes': [models.Index(fields=['viewer', 'target_type'], name='messaging_c_viewer__749d18_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('broker__isnull', False), ('professional__isnull', True), ('target_type', 'BROKER')), models.Q(('broker__isnull', True), ('professional__isnull', False), ('target_type', 'PROFESSIONAL')), _connector='OR'), name='messaging_grant_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('broker__isnull', False), ('revoked_at__isnull', True)), fields=('viewer', 'broker'), name='messaging_active_broker_grant_unique'), models.UniqueConstraint(condition=models.Q(('professional__isnull', False), ('revoked_at__isnull', True)), fields=('viewer', 'professional'), name='messaging_active_professional_grant_unique')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=4000)),
                ('sender_email_snapshot', models.EmailField(max_length=254)),
                ('sender_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('sender_phone_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('is_system', models.BooleanField(default=False)),
                ('privacy_policy_version', models.CharField(blank=True, default='', max_length=16)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='messaging_m_convers_7bc91b_idx'), models.Index(fields=['conversation', 'read_at'], name='messaging_m_convers_636311_idx')],
            },
        ),
    ]
