# Generated by Django 5.2.17 on 2026-09-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_seed_contact_unlock_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaccessgrant',
            name='first_revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
