# Generated by Django 5.2.17 on 2026-09-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_contactaccessgrant_first_revealed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("ARCHIVED", "Archived"),
                    ("BLOCKED", "Blocked"),
                    ("CLOSED", "Closed (account changed)"),
                ],
                default="OPEN",
                max_length=10,
            ),
        ),
    ]
