# Generated by Django 5.2.17 on 2026-09-18 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='DRAFT', max_length=10)),
                ('public_email', models.EmailField(max_length=254)),
                ('public_phone', models.CharField(max_length=32)),
                ('website_url', models.URLField(blank=True, max_length=300, null=True)),
                ('auto_approve_listings', models.BooleanField(default=False)),
                ('auto_approve_changed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_approve_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_auto_approve_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BrokerMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Broker admin'), ('MANAGER', 'Manager'), ('AGENT', 'Agent'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=10)),
                ('can_edit_listings', models.BooleanField(default=False)),
                ('can_manage_team', models.BooleanField(default=False)),
                ('can_read_messages', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_memberships', to=settings.AUTH_USER_MODEL)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='brokers.brokerorganization')),
            ],
            options={
                'ordering': ('broker__name', 'user__email'),
            },
        ),
        migrations.AddConstraint(
            model_name='brokerorganization',
            constraint=models.CheckConstraint(condition=models.Q(('auto_approve_changed_by__isnull', True), ('auto_approve_changed_at__isnull', False), _connector='OR'), name='brokers_auto_approve_actor_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='brokermembership',
            constraint=models.UniqueConstraint(fields=('user', 'broker'), name='brokers_membership_unique_user_broker'),
        ),
        migrations.AddConstraint(
            model_name='brokermembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'ADMIN'), _negated=True), models.Q(('can_edit_listings', True), ('can_manage_team', True), ('can_read_messages', True)), _connector='OR'), name='brokers_admin_membership_has_all_permissions'),
        ),
    ]
