# Generated by Django 5.2.17 on 2026-09-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_broker_directory_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerorganization',
            name='about',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
    ]
