# Generated by Django 5.2.17 on 2026-09-20 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_broker_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('listing_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('seat_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_visibility', models.PositiveSmallIntegerField(choices=[(0, 'Standard'), (1, 'Priority placement'), (2, 'Featured placement')], default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'monthly_price'),
            },
        ),
        migrations.AddField(
            model_name='brokerorganization',
            name='plan_renews_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerorganization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brokers', to='brokers.brokerplan'),
        ),
    ]
