# Generated by Django 5.2.17 on 2026-09-20 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0005_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='brokerplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='brokerplan',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Free days before the first charge; a card is still collected up front. 0 = no trial.'),
        ),
        migrations.CreateModel(
            name='BrokerSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='INACTIVE', max_length=10)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=64)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('trial_used_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('past_due_since', models.DateTimeField(blank=True, null=True)),
                ('broker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='brokers.brokerorganization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('stripe_subscription_id', ''), _negated=True), fields=('stripe_subscription_id',), name='broker_subscription_one_row_per_stripe_subscription')],
            },
        ),
    ]
