# Generated by Django 5.2.17 on 2026-09-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0006_subscription_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerorganization',
            name='cover_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='brokerorganization',
            name='logo_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
