# Generated by Django 5.2.17 on 2026-09-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0007_org_image_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokermembership',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
