# Generated by Django 5.2.17 on 2026-09-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0010_brokerorganization_place_geoname_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokersubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
