# Generated by Django 5.2.17 on 2026-09-25 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0011_subscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='brokerorganization',
            name='trading_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='brokerorganization',
            name='owner_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='brokers.brokerrole'),
        ),
        migrations.CreateModel(
            name='BrokerVerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=300)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='brokers.brokerorganization')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
