# Generated by Django 5.2.17 on 2026-09-17 21:24

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('STRIPE', 'Stripe')], max_length=16)),
                ('action', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=255)),
                ('target_id', models.CharField(max_length=255)),
                ('request_id', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('ADMIN', 'Admin'), ('TASK', 'Task'), ('WEBHOOK', 'Webhook')], max_length=16)),
                ('before', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('after', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__59bbff_idx'), models.Index(fields=['actor_user', '-created_at'], name='audit_audit_actor_u_65f79c_idx')],
            },
        ),
    ]
